### ISSUE TITLE
No response from telegram bot

### ISSUE THREAD

**Issue by Eycxot** [floschnell/flatcrawl-processors#1]
Hi,

since yesterday afternoon the bot on telegram is not responding. Are there any know issues atm? I would like to help.

**Comment by floschnell** [comment]
Hey, thanks for your message. I have been working on getting it back up. Unfortunately the server has been victim of a cyber attack. People have run some bitcoin mining on it 😞 . I reset everything and restarted the containers. Furthermore I enabled tlsverify for the docker REST endpoint, which had been the attack vector (I provided certificates, but did not know that one had to explicitly set tlsverify - this is a design flaw in my eyes...). All user related information are stored in a firebase real-time database. User information that is stored consists of: telegram userid, search criteria and addresses of important places (if provided). Credentials to access the database are injected to the containers during startup, so as I see it, accessing the database has not been possible for the attackers.
It should be fully functioning again.
If you like to help in terms of development, or if you have ideas on how to improve it, then let's discuss this! I don't have too much spare time, but I would definitely be willing to help you setup a development environment, so that you can start to contribute.

**Comment by Eycxot** [comment]
Hi, thanks for your fix! It is working again 🎉🎉🎉

In terms of development, I will try first to set it up with your readme and then try to commit something😅 
I will create PRs if they get into a state where somebody can benefit from.

**Comment by Eycxot** [comment]
Forgot to close the issue 🤦‍♂️
